from Delivery_app_BK.services.general_services.general_creation import create_general_object


from Delivery_app_BK.services.item_services.service_create import service_create_item_category
from Delivery_app_BK.services.item_services.service_create import service_create_item_type
from Delivery_app_BK.services.item_services.service_create import service_create_item_property
from Delivery_app_BK.services.item_services.service_create import service_create_item