"""initial migration

Revision ID: 879322b97798
Revises: 
Create Date: 2025-12-09 15:54:03.629283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879322b97798'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Item_article_number'), ['article_number'], unique=False)

    with op.batch_alter_table('ItemCategory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ItemCategory_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_ItemCategory_name'), ['name'], unique=True)

    with op.batch_alter_table('ItemPosition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemPosition_name'), ['name'], unique=False)

    with op.batch_alter_table('ItemProperty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemProperty_name'), ['name'], unique=False)

    with op.batch_alter_table('ItemState', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemState_name'), ['name'], unique=False)

    with op.batch_alter_table('ItemType', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ItemType_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_ItemType_name'), ['name'], unique=True)

    with op.batch_alter_table('MessageTemplate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MessageTemplate_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_MessageTemplate_content'), ['content'], unique=False)
        batch_op.create_index(batch_op.f('ix_MessageTemplate_name'), ['name'], unique=False)

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Order_client_email'), ['client_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_Order_client_first_name'), ['client_first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Order_client_last_name'), ['client_last_name'], unique=False)
        batch_op.create_index('ix_order_client_address_gin', ['client_address'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_address_tsvector', [sa.literal_column("to_tsvector('simple', client_address::text)")], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_primary_phone_gin', ['client_primary_phone'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_secondary_phone_gin', ['client_secondary_phone'], unique=False, postgresql_using='gin')
        batch_op.drop_column('order_state')

    with op.batch_alter_table('Route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Route_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_Route_route_label'), ['route_label'], unique=False)

    with op.batch_alter_table('RouteState', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_RouteState_name'), ['name'], unique=False)

    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Team_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_Team_name'), ['name'], unique=True)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('User_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_username'), ['username'], unique=False)

    with op.batch_alter_table('UserRoles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserRoles_role'), ['role'], unique=False)

    with op.batch_alter_table('UserVehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserVehicles_name'), ['name'], unique=False)

    with op.batch_alter_table('UserWarehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserWarehouses_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserWarehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserWarehouses_name'))

    with op.batch_alter_table('UserVehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserVehicles_name'))

    with op.batch_alter_table('UserRoles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserRoles_role'))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_username'))
        batch_op.drop_index(batch_op.f('ix_User_email'))
        batch_op.create_unique_constraint(batch_op.f('User_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Team_name'))
        batch_op.create_unique_constraint(batch_op.f('Team_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('RouteState', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_RouteState_name'))

    with op.batch_alter_table('Route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Route_route_label'))
        batch_op.drop_index(batch_op.f('ix_Route_delivery_date'))

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_state', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_order_client_secondary_phone_gin', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_primary_phone_gin', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_address_tsvector', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_address_gin', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_Order_client_last_name'))
        batch_op.drop_index(batch_op.f('ix_Order_client_first_name'))
        batch_op.drop_index(batch_op.f('ix_Order_client_email'))

    with op.batch_alter_table('MessageTemplate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MessageTemplate_name'))
        batch_op.drop_index(batch_op.f('ix_MessageTemplate_content'))
        batch_op.drop_index(batch_op.f('ix_MessageTemplate_channel'))

    with op.batch_alter_table('ItemType', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemType_name'))
        batch_op.create_unique_constraint(batch_op.f('ItemType_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ItemState', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemState_name'))

    with op.batch_alter_table('ItemProperty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemProperty_name'))

    with op.batch_alter_table('ItemPosition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemPosition_name'))

    with op.batch_alter_table('ItemCategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemCategory_name'))
        batch_op.create_unique_constraint(batch_op.f('ItemCategory_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Item_article_number'))

    # ### end Alembic commands ###
