"""added name to templatePrint

Revision ID: ac1fd2d96bd7
Revises: f059aa3f2b44
Create Date: 2025-12-19 15:12:42.515764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1fd2d96bd7'
down_revision = 'f059aa3f2b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserPrintLabelTemplates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserPrintLabelTemplates', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
