"""Inital migration

Revision ID: dbe0a26248b5
Revises: 
Create Date: 2025-12-17 11:01:58.967418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbe0a26248b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('missing_to_configure', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('subscription', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Team_name'), ['name'], unique=True)

    op.create_table('UserRoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('UserRoles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserRoles_role'), ['role'], unique=False)

    op.create_table('EmailSMTP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(), nullable=False),
    sa.Column('smtp_password_encrypted', sa.String(), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('max_per_session', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemcategory_team_name')
    )
    with op.batch_alter_table('ItemCategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemCategory_name'), ['name'], unique=False)

    op.create_table('ItemPosition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemposition_team_name')
    )
    with op.batch_alter_table('ItemPosition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemPosition_name'), ['name'], unique=False)

    op.create_table('ItemProperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemproperty_team_name')
    )
    with op.batch_alter_table('ItemProperty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemProperty_name'), ['name'], unique=False)

    op.create_table('ItemState',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemstate_team_name')
    )
    with op.batch_alter_table('ItemState', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemState_name'), ['name'], unique=False)

    op.create_table('MessageTemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('MessageTemplate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MessageTemplate_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_MessageTemplate_content'), ['content'], unique=False)
        batch_op.create_index(batch_op.f('ix_MessageTemplate_name'), ['name'], unique=False)

    op.create_table('RoleRules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['UserRoles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('RoleRules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_RoleRules_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_RoleRules_role_id'), ['role_id'], unique=False)

    op.create_table('RouteState',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('RouteState', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_RouteState_name'), ['name'], unique=False)

    op.create_table('TwilioMod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twilio_sid', sa.String(), nullable=True),
    sa.Column('twilio_token_encrypted', sa.String(), nullable=True),
    sa.Column('sender_number', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('profile_picture', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('old_team_id', sa.Integer(), nullable=True),
    sa.Column('old_role_id', sa.Integer(), nullable=True),
    sa.Column('show_app_tutorial', sa.Boolean(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('last_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['UserRoles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_username'), ['username'], unique=False)

    op.create_table('UserVehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('travel_mode', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('cost_per_hour', sa.Float(), nullable=True),
    sa.Column('cost_per_kilometer', sa.Float(), nullable=True),
    sa.Column('travel_duration_limit', sa.Integer(), nullable=True),
    sa.Column('route_distance_limit', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('UserVehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserVehicles_name'), ['name'], unique=False)

    op.create_table('UserWarehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('UserWarehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserWarehouses_name'), ['name'], unique=False)

    op.create_table('ItemType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_category_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_category_id'], ['ItemCategory.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemtype_team_name')
    )
    with op.batch_alter_table('ItemType', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItemType_name'), ['name'], unique=False)

    op.create_table('Route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_label', sa.String(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('expected_start_time', sa.String(), nullable=True),
    sa.Column('expected_end_time', sa.String(), nullable=True),
    sa.Column('actual_start_time', sa.String(), nullable=True),
    sa.Column('actual_end_time', sa.String(), nullable=True),
    sa.Column('set_start_time', sa.String(), nullable=True),
    sa.Column('set_end_time', sa.String(), nullable=True),
    sa.Column('start_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('end_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('arrival_time_range', sa.Integer(), nullable=True),
    sa.Column('using_optimization_indx', sa.Integer(), nullable=True),
    sa.Column('saved_optimizations', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('is_optimized', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['RouteState.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Route_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_Route_route_label'), ['route_label'], unique=False)

    op.create_table('TeamInvitesSend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['UserRoles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserTeamInvitationsReceived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=False),
    sa.Column('from_team_name', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['UserRoles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_first_name', sa.String(), nullable=False),
    sa.Column('client_last_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('client_primary_phone', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('client_secondary_phone', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('client_address', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('client_language', sa.String(), nullable=True),
    sa.Column('notes_chat', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('expected_arrival_time', sa.String(), nullable=True),
    sa.Column('actual_arrival_time', sa.String(), nullable=True),
    sa.Column('marketing_messages', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_after', sa.String(), nullable=True),
    sa.Column('delivery_before', sa.String(), nullable=True),
    sa.Column('stop_time', sa.String(), nullable=True),
    sa.Column('in_range', sa.Boolean(), nullable=True),
    sa.Column('delivery_arrangement', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['Route.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Order_client_email'), ['client_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_Order_client_first_name'), ['client_first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Order_client_last_name'), ['client_last_name'], unique=False)
        batch_op.create_index('ix_order_client_address_gin', ['client_address'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_address_tsvector', [sa.literal_column("to_tsvector('simple', client_address::text)")], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_primary_phone_gin', ['client_primary_phone'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_secondary_phone_gin', ['client_secondary_phone'], unique=False, postgresql_using='gin')

    op.create_table('type_property_association',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['ItemProperty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['ItemType.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', 'property_id')
    )
    op.create_table('Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_number', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('item_category', sa.String(), nullable=True),
    sa.Column('item_state_id', sa.Integer(), nullable=True),
    sa.Column('item_position_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('page_link', sa.String(), nullable=True),
    sa.Column('item_valuation', sa.Integer(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('item_position_record', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('item_state_record', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_position_id'], ['ItemPosition.id'], ),
    sa.ForeignKeyConstraint(['item_state_id'], ['ItemState.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Item_article_number'), ['article_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Item_article_number'))

    op.drop_table('Item')
    op.drop_table('type_property_association')
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_client_secondary_phone_gin', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_primary_phone_gin', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_address_tsvector', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_address_gin', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_Order_client_last_name'))
        batch_op.drop_index(batch_op.f('ix_Order_client_first_name'))
        batch_op.drop_index(batch_op.f('ix_Order_client_email'))

    op.drop_table('Order')
    op.drop_table('UserTeamInvitationsReceived')
    op.drop_table('TeamInvitesSend')
    with op.batch_alter_table('Route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Route_route_label'))
        batch_op.drop_index(batch_op.f('ix_Route_delivery_date'))

    op.drop_table('Route')
    with op.batch_alter_table('ItemType', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemType_name'))

    op.drop_table('ItemType')
    with op.batch_alter_table('UserWarehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserWarehouses_name'))

    op.drop_table('UserWarehouses')
    with op.batch_alter_table('UserVehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserVehicles_name'))

    op.drop_table('UserVehicles')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_username'))
        batch_op.drop_index(batch_op.f('ix_User_email'))

    op.drop_table('User')
    op.drop_table('TwilioMod')
    with op.batch_alter_table('RouteState', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_RouteState_name'))

    op.drop_table('RouteState')
    with op.batch_alter_table('RoleRules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_RoleRules_role_id'))
        batch_op.drop_index(batch_op.f('ix_RoleRules_name'))

    op.drop_table('RoleRules')
    with op.batch_alter_table('MessageTemplate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MessageTemplate_name'))
        batch_op.drop_index(batch_op.f('ix_MessageTemplate_content'))
        batch_op.drop_index(batch_op.f('ix_MessageTemplate_channel'))

    op.drop_table('MessageTemplate')
    with op.batch_alter_table('ItemState', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemState_name'))

    op.drop_table('ItemState')
    with op.batch_alter_table('ItemProperty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemProperty_name'))

    op.drop_table('ItemProperty')
    with op.batch_alter_table('ItemPosition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemPosition_name'))

    op.drop_table('ItemPosition')
    with op.batch_alter_table('ItemCategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItemCategory_name'))

    op.drop_table('ItemCategory')
    op.drop_table('EmailSMTP')
    with op.batch_alter_table('UserRoles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserRoles_role'))

    op.drop_table('UserRoles')
    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Team_name'))

    op.drop_table('Team')
    # ### end Alembic commands ###
