"""added UserPrintLabelTemplates

Revision ID: f059aa3f2b44
Revises: dbe0a26248b5
Create Date: 2025-12-19 12:50:23.468117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f059aa3f2b44'
down_revision = 'dbe0a26248b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserPrintLabelTemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_string', sa.Text(), nullable=True),
    sa.Column('template_target', sa.String(), nullable=True),
    sa.Column('timestampt', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserPrintLabelTemplates')
    # ### end Alembic commands ###
